server:
  port: 8080
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        #连接池中的最大空闲连接数 defalut 8
        max-idle: 500
        #连接池中的最小空闲连接数 default 0
        min-idle: 50
        # 如果为-1则不限制，如果已经分配了maxActive个实例则此时pool的状态为耗尽
        max-active: 1000
        #等待可用连接的最大时间，单位毫秒，default -1永不超时
        max-wait: 2000